routes/web.php
<?php
header('Access-Control-Allow-Origin: *');
/*
|--------------------------------------------------------------------------
|     Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/
Auth::routes();

/*
|=============================
|      --/ Admin Area /--      
|=============================
*/
Route::prefix('admin')->group(function()
{ 
  Route::group(['namespace' => 'Admin'], function()
  {
     // Admin 
    Route::get( '/', 'AdminController@index')->name("admin");

    /*****************
    * rezervasyon Routes
    ******************/
    Route::get( '/rezervasyon/list','RezervasyonController@index')->name("rezervasyon.list");
    Route::get( '/rezervasyon/simdiki','RezervasyonController@simdiki')->name("rezervasyon.simdiki");
    Route::get( '/rezervasyon/sonraki','RezervasyonController@sonraki')->name("rezervasyon.sonraki");
    Route::get( '/rezervasyon/gecmis', 'RezervasyonController@gecmis')->name("rezervasyon.gecmis");
    Route::get( '/rezervasyon/dlist','RezervasyonController@all_deleted')->name("rezervasyon.all_deleted");
    Route::get( '/rezervasyon/{rezervasyon}/delete','RezervasyonController@delete')->name("rezervasyon.delete");

    /******************
     * Kort Routes
     ******************/
    Route::get( 
      '/kort/{kort}/tamir','KortController@tamir')
      ->name("kort.tamir");
    Route::get( 
      '/kort/{kort}/mesgul','KortController@mesgul')
      ->name("kort.mesgul");
    Route::get( 
      '/kort/{kort}/calistir','KortController@calistir')
      ->name("kort.calistir");
    Route::get( 
      '/kort/{kort}/rezervasyonlar','KortController@rezervasyonlar')
      ->name("kort.rezervasyonlar");
    Route::get(
      '/kort/dlist','KortController@all_deleted')
      ->name("kort.all_deleted");
      Route::get('/kort/{kort}/delete','KortController@delete')->name("kort.delete");
      Route::post('/kort/{kort}/delete','KortController@p_delete')->name("kort.p_delete");
      Route::get('/kort/{kort}/restore','KortController@restore')->name("kort.restore");
      Route::post('/kort/{kort}/restore','KortController@p_restore')->name("kort.p_restore");
    Route::resource('/kort','KortController');
       

    /*****************
    * kiralayan Routes
    ******************/
    Route::get( '/kiralayan/dlist',  'KiralayanController@all_deleted')->name("kiralayan.all_deleted");
    Route::get( '/kiralayan/{kiralayan}/delete',  'KiralayanController@delete')->name("kiralayan.delete");    
    Route::resource( '/kiralayan',  'KiralayanController');  
   
    /*******************
     * Servis Routes
     ******************/
    Route::get( '/servis/{servi}/tamir',         'ServisController@tamir')->name("servis.tamir");
    Route::get( '/servis/{servi}/mesgul',        'ServisController@mesgul')->name("servis.mesgul");
    Route::get( '/servis/{servi}/calistir',      'ServisController@calistir')->name("servis.calistir");
    Route::get( '/servis/{servi}/rezervasyonlar','ServisController@rezervasyonlar')->name("servis.rezervasyonlar");
    Route::get('/servis/dlist',     'ServisController@all_deleted')->name("servis.all_deleted");
    Route::get('/servis/{servi}/delete', 'ServisController@delete')->name("servis.delete");
    Route::post('/servis/{servi}/delete', 'ServisController@p_delete')->name("servis.p_delete");
    Route::get('/servis/{servi}/restore', 'ServisController@restore')->name("servis.restore");
    Route::post('/servis/{servi}/restore', 'ServisController@p_restore')->name("servis.p_restore");
    Route::resource( '/servis',     'ServisController');
    
    /*****************
    * contacts Routes
    ******************/
    Route::get( '/contacts/{contacts}/delete',  'ContactsController@delete')->name("contacts.delete");    
    Route::get( '/contacts/dlist',  'ContactsController@all_deleted')->name("contacts.all_deleted");
    Route::resource( '/contacts',   'ContactsController');
  
  });
});

/*
|=============================
|      --/ User Area /--      
|=============================
*/

  Route::group(['namespace' => 'User'], function()
  {
    Route::get( 'user/', 'UserController@index')->name("user");
    Route::get( 'user/hesabim', 'UserController@hesabim')->name("hesabim");
    Route::get('/landing',[
        'uses' => 'RezervasyonController@landing',
        'as' => 'get.hours'
    ]);
    Route::post('/info/hours',[
        'uses' => 'RezervasyonController@get_empty_hours',
        'as' => 'ajax'
    ]);

    Route::get('/land',[
        'uses' => 'RezervasyonController@getview'
    ]);

      Route::get('/uzatma/{rezervasyon}',[
          'uses' => 'RezervasyonController@uzatma',
          'as' => 'rezervasyon.uzatma'
      ]);
      Route::get('/bekleme/{rezervasyon}',[
          'uses' => 'RezervasyonController@bekleme',
          'as' => 'rezervasyon.bekleme'
      ]);
    Route::resource( 'user/rezervasyon','RezervasyonController');

  });

/*
|=============================
|      --/ Home  Area /--      
|=============================
*/
  Route::group(['namespace' => 'Home'], function()
  {
    Route::get('/home','HomeController@index')->name('home'); // ana sayfa
    Route::get('/',    'HomeController@index')->name('homepage'); // ana sayfa
    Route::get('/iletisim',      'ContactsController@create')->name('contacts'); // contact sayfa 
    Route::post('/iletisim',      'ContactsController@store')->name('p_contacts'); // contact sayfa 
    Route::get('/hakkimizda',       'HomeController@aboutUs')->name('aboutUs'); // hakkimizde
    Route::get('/prices',        'HomeController@prices')->name('prices'); // kiralama fiyatlari    
    Route::get('/terms',         'HomeController@terms')->name('terms'); // Kurallar
  });




  Route::group(['namespace' => 'Settings'], function()
{
  Route::get('lang/{lang}', 'LanguageController@index')->name('lang');
});

/*
|=============================
|      --/Account Area /--      
|=============================
*/
    Route::prefix('account')->group(function()
    {
      Route::group(['namespace' => 'Account'], function()
        {
          Route::get ('/profile',         'AccountController@showprofile')->name("profile");
          Route::post('/profile',         'AccountController@profile')->name("post_profile");
          Route::get ('/change-password',  'AccountController@showchangePassword')->name('changePassword');;
          Route::post('/change-password',  'AccountController@changePassword')->name('post_changePassword');
        }
      );
    }
  );

app/Http/Controllers/Admin/KortController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Http\Models\Kort;
use Illuminate\Http\Request;
use App\Http\Requests\KortValidation;
use Session;
class KortController extends Controller
{   
    public function __construct()
    {
      $this->middleware(['auth','admin']);
    }
   
    public function index()
    {
        $kortlar = Kort::all_list();
        return view('admin.kort.index',compact('kortlar'));
    }
    public function all_deleted()
    {
        $kortlar = Kort::all_deleted();
        return view('admin.kort.index',compact('kortlar'));
    }
    public function tamir(Kort $kort)
    {
        $kort->durum = 2 ;
        $kort->save();
        return back();
    }
    public function mesgul(Kort $kort)
    {
        $kort->durum = 1 ;
        $kort->save();
        return back();
    }
    public function calistir(Kort $kort)
    {
        $kort->durum = 0 ;
        $kort->save();
        return back();
    }
  
    public function create()
    {
        return  view('admin.kort.create');
    }

    
    public function store(KortValidation $request)
    {
        $kort = new Kort;
        $kort->fill($request->all());
        $kort->save();
        return redirect()->route('kort.index');
    }


    public function show(Kort $kort)
    {
        return  view('admin.kort.show');
    }
    
    public function edit(Kort $kort)
    {
        return  view('admin.kort.edit',compact('kort'));
    }


    public function update(KortValidation $request, Kort $kort)
    {
        $kort->update($request->all());
        Session::flash('success','işlem başarile gerçekleştirilmiştir');
        return redirect()->route('kort.index');
    }

   
    public function delete(Kort $kort)
    {
        return view('admin.kort.delete',compact('kort'));
	}
	public function p_delete( Kort $kort)
    {
		$kort->durum=9;
		$kort->save();
		Session::flash('success',$kort->isim.' kort belgileri basarile silindi');        
		return redirect()->route('kort.index');
	}
	public function restore(Kort $kort)
    {
        return view('admin.kort.delete',compact('kort'));
	}
	public function p_restore(Kort $kort)
    {
		$kort->durum=0;
		$kort->save();
		Session::flash('success',$kort->isim.' kort belgileri basarile silindi');        
		return redirect()->route('kort.index');
    }
    public function destroy(Kort $kort)
    {
        $isim=$kort->isim;
        $kort->delete($kort);
        Session::flash('success',$isim.' kort belgileri basarile silinmiş');        
        return back();
    }
    
}

resources/views/admin/kort/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Kort Ekle</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>
                    <a href="KortlarListesi.html">Kortlar Listesi</a>
                </li>
                <li class="active">
                    <strong>Kort Ekle</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    
                    <div class="ibox-content">
                        <form action="{{ route('kort.store') }}" method="post" class="form-horizontal">
                            @csrf
                            <div class="form-group">
                                <label for="isim" class="col-sm-2 control-label">Kort Adı</label>
                                <div class="col-sm-10">
                                        <input type="text"  id="isim" name="isim"  class="form-control {{ $errors->has('isim') ? ' is-invalid' : '' }}"  value="{{ old('isim') }}" required autofocus>
                                        @if ($errors->has('isim'))
                                        <span class="invalid-feedback">
                                            <strong>{{ $errors->first('isim') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Kort Tipi</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" name="type">
                                        <option value="0"  >Seç</option>
                                        <option value="0" @if(old('type')==0 ) selected @endif>Tekli</option>
                                        <option value="1" @if(old('type')==1 ) selected @endif  >Çift</option>
                                    </select>
                                    @if ($errors->has('type'))
                                        <span class="invalid-feedback">
                                            <strong>{{ $errors->first('type') }}</strong>
                                        </span>
                                     @endif 
                                </div>
                            </div>
                           
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Saat Ucreti</label>
                                <div class="col-sm-10">
                                    <div class="input-group m-b">
                                        <span class="input-group-addon">$</span>
                                         <input type="text"  id="saat_ucreti" name="saat_ucreti"  class="form-control {{ $errors->has('saat_ucreti') ? ' is-invalid' : '' }}"  value="{{ old('saat_ucreti') }}" required autofocus>
                                        @if ($errors->has('saat_ucreti'))
                                            <span class="invalid-feedback">
                                                <strong>{{ $errors->first('saat_ucreti') }}</strong>
                                            </span>
                                        @endif
                                          <span class="input-group-addon">.00</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Saat Puanı</label>
                                <div class="col-sm-10">
                                    <div class="input-group m-b">
                                        <span class="input-group-addon">P</span> 
                                        <input type="text"  id="saat_puani" name="saat_puani"  class="form-control {{ $errors->has('saat_puani') ? ' is-invalid' : '' }}"  value="{{ old('saat_puani') }}" required autofocus>
                                        @if ($errors->has('saat_puani'))
                                            <span class="invalid-feedback">
                                                <strong>{{ $errors->first('saat_puani') }}</strong>
                                            </span>
                                         @endif 
                                        <span class="input-group-addon">.00</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Kort Durumu</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" name="durum">
                                        <option value="0"  >Seç</option>
                                        <option value="0" @if(old('durum')==0 ) selected @endif>Hazır</option>
                                        <option value="1" @if(old('durum')==1 ) selected @endif>Meşgul</option>
                                        <option value="2" @if(old('durum')==2 ) selected @endif>Tamirde</option>
                                    </select>
                                    @if ($errors->has('durum'))
                                        <span class="invalid-feedback">
                                            <strong>{{ $errors->first('durum') }}</strong>
                                        </span>
                                    @endif 
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    {{-- <button class="btn btn-white" type="submit">Cancel</button> --}}
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/kort/delete.blade.php
{{-- @extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Delete   {{ $kort->isim }} Kort</div>

                <div class="card-body">
                    Are You Sure You Want to delete this asshole kort!
                    <form action="{{ route('kort.destroy',$kort) }}" method="post">
                        @method('delete')
                        @csrf
                        <input type="submit" value="delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection --}}



@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">
                            @if(Route::is('kort.delete'))
                            Delete 
                            @else
                            Aktif 
                            @endif
                             <span class="text-danger"> {{ $kort->isim }} </span> kort
                    </h2>
                </div>
                <div class="panel panel-body card-body">
                    <div class="col-md-8 col-md-offset-2">
                    @if(Route::is('kort.delete'))
                    <h4 class="text-danger">{{ $kort->isim }} korti Silmek istediğine emin misiniz ?</h4>
                    <form action="{{ route('kort.p_delete',$kort) }}" method="post">
                        @csrf
                    <div class="text-right">
                        <button type="submit" class="btn btn-danger"><i class="fa fa-2x fa-trash"></i> Sil</button>
                    </div>
                    </form>
                    @elseif(Route::is('kort.restore'))
                    <h4 class="text-success">{{ $kort->isim }} korti aktiflemek istediğine emin misiniz ?</h4>
                    <form action="{{ route('kort.p_restore',$kort) }}" method="post">
                        @csrf
                    <div class="text-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-2x fa-check"></i> aktif</button>
                    </div>
                    </form>
                    @endif
                    <a href="{{ route('kort.index') }}" class="btn btn-default">geri dön</a>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/kort/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    
                    <div class="ibox-content">
                            <form action="{{ route('kort.update',$kort->id) }}" method="post" class="form-horizontal">
                                    @csrf
                                {{ method_field('put') }}
                                    
                                    <div class="form-group">
                                        <label for="isim" class="col-sm-2 control-label">Kort Adı</label>
                                        <div class="col-sm-10">
                                                <input type="text"  id="isim" name="isim"  class="form-control {{ $errors->has('isim') ? ' is-invalid' : '' }}"  value="{{ $kort->isim }}" required autofocus>
                                                @if ($errors->has('isim'))
                                                <span class="invalid-feedback">
                                                    <strong>{{ $errors->first('isim') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Kort Tipi</label>
                                        <div class="col-sm-10">
                                            <select class="form-control m-b" name="type">
                                                <option value="0" >Seç</option>
                                                <option value="0"  @if($kort->type==0) selected @endif>Tekli</option>
                                                <option value="1"  @if($kort->type==1) selected @endif>Çift</option>
                                            </select>
                                            @if ($errors->has('type'))
                                                <span class="invalid-feedback">
                                                    <strong>{{ $errors->first('type') }}</strong>
                                                </span>
                                             @endif 
                                        </div>
                                    </div>
                                   
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Saat Ucreti</label>
                                        <div class="col-sm-10">
                                            <div class="input-group m-b">
                                                <span class="input-group-addon">$</span>
                                                 <input type="text"  id="saat_ucreti" name="saat_ucreti"  class="form-control {{ $errors->has('saat_ucreti') ? ' is-invalid' : '' }}"  value="{{ $kort->saat_ucreti }}" required autofocus>
                                                @if ($errors->has('saat_ucreti'))
                                                    <span class="invalid-feedback">
                                                        <strong>{{ $errors->first('saat_ucreti') }}</strong>
                                                    </span>
                                                @endif
                                                  <span class="input-group-addon">.00</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Saat Puanı</label>
                                        <div class="col-sm-10">
                                            <div class="input-group m-b">
                                                <span class="input-group-addon">P</span> 
                                                <input type="text"  id="saat_puani" name="saat_puani"  class="form-control {{ $errors->has('saat_puani') ? ' is-invalid' : '' }}"  value="{{ $kort->saat_puani }}" required autofocus>
                                                @if ($errors->has('saat_puani'))
                                                    <span class="invalid-feedback">
                                                        <strong>{{ $errors->first('saat_puani') }}</strong>
                                                    </span>
                                                 @endif 
                                                <span class="input-group-addon">.00</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Kort Durumu</label>
                                        <div class="col-sm-10">
                                            <select class="form-control m-b" name="durum">
                                                <option value="0"  >Seç</option>
                                                <option value="0" @if($kort->durum==0) selected @endif>Hazır</option>
                                                <option value="1" @if($kort->durum==1) selected @endif>Meşgul</option>
                                                <option value="2" @if($kort->durum==2) selected @endif>Tamirde</option>
                                            </select>
                                            @if ($errors->has('durum'))
                                                <span class="invalid-feedback">
                                                    <strong>{{ $errors->first('durum') }}</strong>
                                                </span>
                                            @endif 
                                        </div>
                                    </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="submit">Cancel</button>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection