routes/web.php
<?php
header('Access-Control-Allow-Origin: *');
/*
|--------------------------------------------------------------------------
|     Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/
Auth::routes();

/*
|=============================
|      --/ Admin Area /--      
|=============================
*/
Route::prefix('admin')->group(function()
{ 
  Route::group(['namespace' => 'Admin'], function()
  {
     // Admin 
    Route::get( '/', 'AdminController@index')->name("admin");

    /*****************
    * rezervasyon Routes
    ******************/
    Route::get( '/rezervasyon/list','RezervasyonController@index')->name("rezervasyon.list");
    Route::get( '/rezervasyon/simdiki','RezervasyonController@simdiki')->name("rezervasyon.simdiki");
    Route::get( '/rezervasyon/sonraki','RezervasyonController@sonraki')->name("rezervasyon.sonraki");
    Route::get( '/rezervasyon/gecmis', 'RezervasyonController@gecmis')->name("rezervasyon.gecmis");
    Route::get( '/rezervasyon/dlist','RezervasyonController@all_deleted')->name("rezervasyon.all_deleted");
    Route::get( '/rezervasyon/{rezervasyon}/delete','RezervasyonController@delete')->name("rezervasyon.delete");

    /******************
     * Kort Routes
     ******************/
    Route::get( 
      '/kort/{kort}/tamir','KortController@tamir')
      ->name("kort.tamir");
    Route::get( 
      '/kort/{kort}/mesgul','KortController@mesgul')
      ->name("kort.mesgul");
    Route::get( 
      '/kort/{kort}/calistir','KortController@calistir')
      ->name("kort.calistir");
    Route::get( 
      '/kort/{kort}/rezervasyonlar','KortController@rezervasyonlar')
      ->name("kort.rezervasyonlar");
    Route::get(
      '/kort/dlist','KortController@all_deleted')
      ->name("kort.all_deleted");
      Route::get('/kort/{kort}/delete','KortController@delete')->name("kort.delete");
      Route::post('/kort/{kort}/delete','KortController@p_delete')->name("kort.p_delete");
      Route::get('/kort/{kort}/restore','KortController@restore')->name("kort.restore");
      Route::post('/kort/{kort}/restore','KortController@p_restore')->name("kort.p_restore");
    Route::resource('/kort','KortController');
       

    /*****************
    * kiralayan Routes
    ******************/
    Route::get( '/kiralayan/dlist',  'KiralayanController@all_deleted')->name("kiralayan.all_deleted");
    Route::get( '/kiralayan/{kiralayan}/delete',  'KiralayanController@delete')->name("kiralayan.delete");    
    Route::resource( '/kiralayan',  'KiralayanController');  
   
    /*******************
     * Servis Routes
     ******************/
    Route::get( '/servis/{servi}/tamir',         'ServisController@tamir')->name("servis.tamir");
    Route::get( '/servis/{servi}/mesgul',        'ServisController@mesgul')->name("servis.mesgul");
    Route::get( '/servis/{servi}/calistir',      'ServisController@calistir')->name("servis.calistir");
    Route::get( '/servis/{servi}/rezervasyonlar','ServisController@rezervasyonlar')->name("servis.rezervasyonlar");
    Route::get('/servis/dlist',     'ServisController@all_deleted')->name("servis.all_deleted");
    Route::get('/servis/{servi}/delete', 'ServisController@delete')->name("servis.delete");
    Route::post('/servis/{servi}/delete', 'ServisController@p_delete')->name("servis.p_delete");
    Route::get('/servis/{servi}/restore', 'ServisController@restore')->name("servis.restore");
    Route::post('/servis/{servi}/restore', 'ServisController@p_restore')->name("servis.p_restore");
    Route::resource( '/servis',     'ServisController');
    
    /*****************
    * contacts Routes
    ******************/
    Route::get( '/contacts/{contacts}/delete',  'ContactsController@delete')->name("contacts.delete");    
    Route::get( '/contacts/dlist',  'ContactsController@all_deleted')->name("contacts.all_deleted");
    Route::resource( '/contacts',   'ContactsController');
  
  });
});

/*
|=============================
|      --/ User Area /--      
|=============================
*/

  Route::group(['namespace' => 'User'], function()
  {
    Route::get( 'user/', 'UserController@index')->name("user");
    Route::get( 'user/hesabim', 'UserController@hesabim')->name("hesabim");
    Route::get('/landing',[
        'uses' => 'RezervasyonController@landing',
        'as' => 'get.hours'
    ]);
    Route::post('/info/hours',[
        'uses' => 'RezervasyonController@get_empty_hours',
        'as' => 'ajax'
    ]);

    Route::get('/land',[
        'uses' => 'RezervasyonController@getview'
    ]);

      Route::get('/uzatma/{rezervasyon}',[
          'uses' => 'RezervasyonController@uzatma',
          'as' => 'rezervasyon.uzatma'
      ]);
      Route::get('/bekleme/{rezervasyon}',[
          'uses' => 'RezervasyonController@bekleme',
          'as' => 'rezervasyon.bekleme'
      ]);
    Route::resource( 'user/rezervasyon','RezervasyonController');

  });

/*
|=============================
|      --/ Home  Area /--      
|=============================
*/
  Route::group(['namespace' => 'Home'], function()
  {
    Route::get('/home','HomeController@index')->name('home'); // ana sayfa
    Route::get('/',    'HomeController@index')->name('homepage'); // ana sayfa
    Route::get('/iletisim',      'ContactsController@create')->name('contacts'); // contact sayfa 
    Route::post('/iletisim',      'ContactsController@store')->name('p_contacts'); // contact sayfa 
    Route::get('/hakkimizda',       'HomeController@aboutUs')->name('aboutUs'); // hakkimizde
    Route::get('/prices',        'HomeController@prices')->name('prices'); // kiralama fiyatlari    
    Route::get('/terms',         'HomeController@terms')->name('terms'); // Kurallar
  });




  Route::group(['namespace' => 'Settings'], function()
{
  Route::get('lang/{lang}', 'LanguageController@index')->name('lang');
});

/*
|=============================
|      --/Account Area /--      
|=============================
*/
    Route::prefix('account')->group(function()
    {
      Route::group(['namespace' => 'Account'], function()
        {
          Route::get ('/profile',         'AccountController@showprofile')->name("profile");
          Route::post('/profile',         'AccountController@profile')->name("post_profile");
          Route::get ('/change-password',  'AccountController@showchangePassword')->name('changePassword');;
          Route::post('/change-password',  'AccountController@changePassword')->name('post_changePassword');
        }
      );
    }
  );

app/Http/Controllers/Admin/RezervasyonController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;


use App\Http\Models\bekleyen;
use App\Http\Models\Kort;
use App\Http\Models\Rezervasyon;

use App\Http\Models\Servis;
use Illuminate\Http\Request;
use App\Http\Requests\RezervasyonValidation;
use Session;
use Carbon\Carbon;

class RezervasyonController extends Controller
{
    
    public function __construct()
    {
      $this->middleware(['auth','admin']);
    }
    public function index()
    {
        // return Rezervasyon::all();
        $classes = ['Kort','Servis'];
        $class_ = isset($_GET['c']) ? $_GET['c'] : null ;
        $id = isset($_GET['i']) ? $_GET['i'] : null   ;

        if($class_ && $id){
            if(in_array($class_,$classes)){
                $class = "\App\Http\Models\\".$class_;
                if( $c = $class::find($id)){
                    $rezervasyonlar = Rezervasyon::all_list();
                    $gecmisler = Rezervasyon::gecmis()->where(strtolower($class_).'_id', '=',$id);
                    $sonrakiler= Rezervasyon::sonraki()->where(strtolower($class_).'_id', '=',$id);
                    $simdikiler= Rezervasyon::simdiki()->where(strtolower($class_).'_id', '=',$id);
                }else
                    Session::flash('error','kayit bulunmadi') ;
            }else
                Session::flash('error','none valid class name') ;
        }else{
            $rezervasyonlar = Rezervasyon::all_list();
            $gecmisler = Rezervasyon::gecmis();
            $sonrakiler= Rezervasyon::sonraki();
            $simdikiler= Rezervasyon::simdiki();
            $tumgelecekler= Rezervasyon::tumgelecek();
        }
        $bekleyenler = Bekleyen::all();
        return view('admin.rezervasyon.index',compact([
            'rezervasyonlar',
            'gecmisler',
            'sonrakiler',
            'simdikiler',
            'tumgelecekler',
            'bekleyenler',
        ]));

    }
    
    public function all_deleted()
    {
        $rezervasyonlar =  Rezervasyon::all_deleted();
        return view('admin.rezervasyon.index',compact('rezervasyonlar'));
    }
    public function simdiki()
    {
        $simdikiler = Rezervasyon::simdiki();
        return view('admin.rezervasyon.simdiki',compact('simdikiler'));
    }
    public function sonraki()
    {
        $sonrakiler = Rezervasyon::sonraki();
        return view('admin.rezervasyon.sonraki',compact('sonrakiler'));
    }
    public function gecmis()
    {
        $gecmisler = Rezervasyon::gecmis();
        return view('admin.rezervasyon.gecmis',compact('gecmisler'));
    }
    
    public function create()
    {
        
    }
    public function store(RezervasyonValidation $request)
    {
    }

   
    public function show(Rezervasyon $rezervasyon)
    {
    }

    
    public function edit(Rezervasyon $rezervasyon)
    {

    }

    public function update(RezervasyonValidation $request, Rezervasyon $rezervasyon)
    {

    }
    public function destroy(Rezervasyon $rezervasyon)
    {
        $time=$rezervasyon->baslangis;
        $rezervasyon->delete();
        Session::flash('success',$time.' rezervasyounu belgileri basarile silinmiştir');        
        return back();
    }
}

app/Http/Controllers/User/RezervasyonController.php
<?php

namespace App\Http\Controllers\User;


use App\Http\Controllers\Controller;
use App\Http\Models\bekleyen;
use App\Http\Models\Kiralayan;
use App\Http\Models\Kort;
use App\Http\Models\Rezervasyon;
use App\Http\Models\Servis;
use App\Http\Requests\RezervasyonValidation;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;


class RezervasyonController extends Controller
{
   
    public function index()
    {
        $rezervasyonlar = Rezervasyon::all_list();
        $gecmisler = Rezervasyon::gecmis();
        $sonrakiler= Rezervasyon::sonraki();
        $simdikiler= Rezervasyon::simdiki();
        $tumgelecekler= Rezervasyon::tumgelecek();
        $bekleyenler = Bekleyen::all();
        return view('admin.rezervasyon.index', compact([
            'rezervasyonlar',
            'gecmisler',
            'sonrakiler',
            'simdikiler',
            'tumgelecekler',
            'bekleyenler',
        ]));
    }


    public function create()
    {
        $rezervasyonlar = Rezervasyon::all();
        $kortlar = Kort::all();
        $servisler = Servis::all();
        return view('admin.rezervasyon.create', compact([
            'rezervasyonlar',
            'kortlar',
            'servisler'

        ]));
    }

    public function store(RezervasyonValidation $request)
    {
        $tarih = $request->tarih;
        $saat = $request->saat;
        if(!$tarih){
            Session::flash('error', "lutfen tarih secin "); 
            return back();
        }
        if(!$saat){
            Session::flash('error', "lutfen saat secin "); 
            return back();
        }

        $saat = substr($saat, 0, strpos($saat, ' '));
        $baslangis_saati = $tarih . ' ' . $saat . ':00';
        $baslangis_saati = Carbon::parse($baslangis_saati);
        $bitis_saati = Carbon::parse($baslangis_saati)->addHour();

        if ($request->telefon && $request->isim)
         {
            $kiralayan = new Kiralayan();
            $kiralayan->fill($request->all());
            $kiralayan->save();
            $kiralayan_id = $kiralayan->id;
        } 
        elseif(Auth::id())
            $kiralayan_id = Auth::id();
        else
        Session::flash('error', "Hata olustu ");
        
        $bos_servisler = Servis::musaitServisler($baslangis_saati);
        
       $rezerv= DB::Insert('call add_rezervasyon(?,?,?,?,?,?)', [
            $request->kort_id,
            $kiralayan_id,
            $baslangis_saati,
            $bitis_saati,
            $request->servis_adresi,
            $bos_servisler[0]
        ]);
        $kiralaya = Kiralayan::find($kiralayan_id);
        if($rezerv)
        Session::flash('success', "sayin {$kiralaya->isim} rezervasyon basariyla olusturulmustur { $baslangis_saati }");
        else
        Session::flash('error', "Hata olustu "); 

        return back();
    }

    public function iptal(Rezervasyon $rezervasyon)
    {
        Rezervasyon::iptal($rezervasyon);
        Session::flash('success', 'iptal isleminiz gerceklestirildi');
        return back();
    }

    public function show(Rezervasyon $rezervasyon)
    {
        //
    }


    public function edit(Rezervasyon $rezervasyon)
    {
        //
    }

    public function update(RezervasyonValidation $request, Rezervasyon $rezervasyon)
    {
        //
    }
    public function destroy(Rezervasyon $rezervasyon)
    {
        $time=$rezervasyon->baslangis;
        $rezervasyon->delete();
        Session::flash('success',$time.' rezervasyounu belgileri basarile silinmiştir');        
        return back();
    }
   

    public function getview()
    {
        return view('home.rezervasyon');
    }

    public function get_empty_hours(Request $request)
    {
        $day =    $request->day;  // request gunu 
        $month =  $request->month;// request ayı
        $year =   $request->year; // request yılı

        $date= Carbon::parse("$year-$month-$day"); // requestin tum tarihi
       
        $sonraki_saat =$n= Carbon::now()->hour+1; // simdiki sattan bir saat sonra           
        // eger bugunku tarihi şimdiki saat al else sabah saat 9 Al
        $n=($date == Today())? $sonraki_saat : 9; 
        // aktive saatler tanimlama
        $av_hours = [];
        for($i=$n;$i<20;$i++)
            $av_hours[]=$i;

        $rezervasyons = DB::table('rezervasyons')
            ->whereDate('baslangis', '=', $date)
            ->where('kort_id', '=', $request->kort)
            ->pluck('baslangis')->toArray();
        foreach ($rezervasyons as $rez_time) 
        {
            $rez_time= Carbon::parse($rez_time);
            $index = array_search($rez_time->hour, $av_hours);
            if ( $index !== false)
                $av_hours[$index] = 0;
        }
        $av_saat = [];
        foreach ($av_hours as $av_hour) 
        {    
            if ($av_hour != 0)
                $av_saat[] = $av_hour;
        }
        $av_saat= ($date < Today())? "" : $av_saat; 
        return response()->json($av_saat);
    }

    public function landing()
    {
        $kortlar = Kort::all_list();
        return view('home.landing', compact([
            'kortlar'
        ]));
    }
    public function uzatma(Rezervasyon $rezervasyon)
    {
        if ($rezervasyon->uzatabilir()) {
            $yeni_rezervasyon = new Rezervasyon();
            $yeni_rezervasyon->fill($rezervasyon->toArray());
            $yeni_rezervasyon->baslangis = $rezervasyon->bitis;
            $yeni_rezervasyon->servis_id = NULL;
            $yeni_rezervasyon->servis_adresi = NULL;
            $yeni_rezervasyon->bitis = Carbon::parse($rezervasyon->bitis)->addHour();
            $yeni_rezervasyon->save();
            Session::flash('success', 'uzatma isleminiz basarile ulasilmistir');
        } else
            Session::flash('error', 'bir hata olustu ');
        return back();
    }

    public function bekleme(Rezervasyon $rezervasyon)
    {
        if ($rezervasyon->suan())
        {
            $bekleyen = new Bekleyen();
            $bekleyen->user_id = $rezervasyon->kiralayan_id;
            $bekleyen->save();
            Session::flash('success', 'bekleme listesine alindi');
        } 
        else
            Session::flash('error', 'bir hata olustu ');
        return back();
    }
}

resources/views/admin/rezervasyon/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">create rezervasyon</div>
                <form action="{{ route('rezervasyon.store') }}" method="post" class="form-horizontal">
                    @csrf
                    @guest
                        <div class="form-group">
                            <label for="isim" class="col-sm-2 control-label">isim</label>
                            <div class="col-sm-10">
                                <input type="text" name="isim" id="isim" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="isim" class="col-sm-2 control-label">Telefon</label>
                            <div class="col-sm-10">
                                <input type="text" name="telefon" id="telefon" class="form-control">
                            </div>
                        </div>
                    @endguest


                    <div class="form-group">
                        <label for="isim" class="col-sm-2 control-label">Kort</label>
                        <div class="col-sm-10">
                            <select name="kort_id" id="kort_id" class="form-control">
                                @foreach($kortlar as $kort)
                                    <option value="{{ $kort->id }}">{{ $kort->isim }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    {{--<div class="form-group">--}}
                        {{--<label for="isim" class="col-sm-2 control-label">Servis</label>--}}
                        {{--<div class="col-sm-10">--}}
                            {{--<select name="kort" id="kort" class="form-control">--}}
                                {{--@foreach($servisler as $servis)--}}
                                    {{--<option value="{{ $servis->id }}">{{ $servis->isim }}</option>--}}
                                {{--@endforeach--}}
                            {{--</select>--}}
                        {{--</div>--}}
                    {{--</div>--}}

                    {{--<div class="form-group">--}}
                        <label for="isim" class="col-sm-2 control-label">Adres</label>
                        <div class="col-sm-10">
                            <input type="text" name="adres" id="adres" class="form-control">
                        </div>
                    </div>



                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            {{-- <button class="btn btn-white" type="submit">Cancel</button> --}}
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/rezervasyon/delete.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Delete rezervasyon</div>

                <div class="card-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/rezervasyon/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">edit rezervasyon</div>

                <div class="card-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/rezervasyon/gecmis.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
    
 
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Tüm Geçmiş Rezevasyonlar</h5>
                </div>
                <div class="ibox-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Kort</th>
                                <th>Rezerv Eden</th>
                                <th>Rezerv Tel</th>
                                <th>Rezerv Süresi</th>
                                <th>Ödenecek</th>
                                <th>Servis Adresi</th>
                                <th>Servis Plakası</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($gecmisler as $rezv )
                            <tr>
                                <td>{{ $rezv->id}} </td>
                                <td>
                                    @if($rezv->kort->type ==1)
                                        Tek'li Kort
                                    @else
                                        Çift'li Kort
                                    @endif
                                </td>
                                <td>{{ $rezv->kiralayan->isim }}</td>
                                <td>{{ $rezv->kiralayan->telefon }}</td>
                                {{--<td>1 saat</td>--}}
                                <td>{{ $rezv->odenecek}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/rezervasyon/simdiki.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
    
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Şimdiki Dilim Zamanındaki Kortlar</h5>
                </div>
                <div class="ibox-content">
                    @if(count($simdikiler)>0)
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Kort</th>
                            <th>Rezerv Eden</th>
                            <th>Rezerv Tel</th>
                            <th>Rezerv Süresi</th>
                            <th>Ödenecek</th>
                        </tr>
                        </thead>
                        <tbody>
                       @foreach($simdikiler as $rezv )
                            <tr>
                        <td>{{ $rezv->id}} </td>
                            <td>
                                @if($rezv->kort->type ==1)
                                    Tek'li Kort
                                @else
                                    Çift'li Kort
                                @endif
                            </td>
                            <td>{{ $rezv->kiralayan->isim }}</td>
                            <td>{{ $rezv->kiralayan->telefon }}</td>
                            <td>1 saat</td>
                            <td>{{ $rezv->odenecek }}</td>
                       
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @else
                    <div class="text danger"> her hangi bir kayit bulunmadi . </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
  
</div>

@endsection

resources/views/admin/rezervasyon/sonraki.blade.php
@extends('layouts.admin')
@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
 
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Sonraki Dilim Zamanındaki Kortlar</h5>
                </div>
                <div class="ibox-content">
                   @if($sonrakiler)
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Kort</th>
                                <th>Rezerv Eden</th>
                                <th>Rezerv Tel</th>
                                <th>Rezerv Süresi</th>
                                <th>Ödenecek</th>
                                <th>Servis Adresi</th>

                            </tr>
                        </thead>
                        <tbody>
                        @foreach($sonrakiler as $rezv )
                            <tr>
                                <td> </td>
                                <td>
                                    @if($rezv->kort->type ==1)
                                        Tek'li Kort
                                    @else
                                        Çift'li Kort
                                    @endif
                                </td>
                                <td>{{ $rezv->kiralayan->isim }}</td>
                                <td>{{ $rezv->kiralayan->telefon }}</td>
                                <td>1 saat</td>
                                <td>{{ $rezv->odenecek}}</td>
                                <td>{{ $rezv->servis_adresi }}</td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @else
                        <div class="text danger"> her hangi bir kayit bulunmadi . </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@endsection