routes/web.php
<?php
header('Access-Control-Allow-Origin: *');
/*
|--------------------------------------------------------------------------
|     Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/
Auth::routes();

/*
|=============================
|      --/ Admin Area /--      
|=============================
*/
Route::prefix('admin')->group(function()
{ 
  Route::group(['namespace' => 'Admin'], function()
  {
     // Admin 
    Route::get( '/', 'AdminController@index')->name("admin");

    /*****************
    * rezervasyon Routes
    ******************/
    Route::get( '/rezervasyon/list','RezervasyonController@index')->name("rezervasyon.list");
    Route::get( '/rezervasyon/simdiki','RezervasyonController@simdiki')->name("rezervasyon.simdiki");
    Route::get( '/rezervasyon/sonraki','RezervasyonController@sonraki')->name("rezervasyon.sonraki");
    Route::get( '/rezervasyon/gecmis', 'RezervasyonController@gecmis')->name("rezervasyon.gecmis");
    Route::get( '/rezervasyon/dlist','RezervasyonController@all_deleted')->name("rezervasyon.all_deleted");
    Route::get( '/rezervasyon/{rezervasyon}/delete','RezervasyonController@delete')->name("rezervasyon.delete");

    /******************
     * Kort Routes
     ******************/
    Route::get( 
      '/kort/{kort}/tamir','KortController@tamir')
      ->name("kort.tamir");
    Route::get( 
      '/kort/{kort}/mesgul','KortController@mesgul')
      ->name("kort.mesgul");
    Route::get( 
      '/kort/{kort}/calistir','KortController@calistir')
      ->name("kort.calistir");
    Route::get( 
      '/kort/{kort}/rezervasyonlar','KortController@rezervasyonlar')
      ->name("kort.rezervasyonlar");
    Route::get(
      '/kort/dlist','KortController@all_deleted')
      ->name("kort.all_deleted");
      Route::get('/kort/{kort}/delete','KortController@delete')->name("kort.delete");
      Route::post('/kort/{kort}/delete','KortController@p_delete')->name("kort.p_delete");
      Route::get('/kort/{kort}/restore','KortController@restore')->name("kort.restore");
      Route::post('/kort/{kort}/restore','KortController@p_restore')->name("kort.p_restore");
    Route::resource('/kort','KortController');
       

    /*****************
    * kiralayan Routes
    ******************/
    Route::get( '/kiralayan/dlist',  'KiralayanController@all_deleted')->name("kiralayan.all_deleted");
    Route::get( '/kiralayan/{kiralayan}/delete',  'KiralayanController@delete')->name("kiralayan.delete");    
    Route::resource( '/kiralayan',  'KiralayanController');  
   
    /*******************
     * Servis Routes
     ******************/
    Route::get( '/servis/{servi}/tamir',         'ServisController@tamir')->name("servis.tamir");
    Route::get( '/servis/{servi}/mesgul',        'ServisController@mesgul')->name("servis.mesgul");
    Route::get( '/servis/{servi}/calistir',      'ServisController@calistir')->name("servis.calistir");
    Route::get( '/servis/{servi}/rezervasyonlar','ServisController@rezervasyonlar')->name("servis.rezervasyonlar");
    Route::get('/servis/dlist',     'ServisController@all_deleted')->name("servis.all_deleted");
    Route::get('/servis/{servi}/delete', 'ServisController@delete')->name("servis.delete");
    Route::post('/servis/{servi}/delete', 'ServisController@p_delete')->name("servis.p_delete");
    Route::get('/servis/{servi}/restore', 'ServisController@restore')->name("servis.restore");
    Route::post('/servis/{servi}/restore', 'ServisController@p_restore')->name("servis.p_restore");
    Route::resource( '/servis',     'ServisController');
    
    /*****************
    * contacts Routes
    ******************/
    Route::get( '/contacts/{contacts}/delete',  'ContactsController@delete')->name("contacts.delete");    
    Route::get( '/contacts/dlist',  'ContactsController@all_deleted')->name("contacts.all_deleted");
    Route::resource( '/contacts',   'ContactsController');
  
  });
});

/*
|=============================
|      --/ User Area /--      
|=============================
*/

  Route::group(['namespace' => 'User'], function()
  {
    Route::get( 'user/', 'UserController@index')->name("user");
    Route::get( 'user/hesabim', 'UserController@hesabim')->name("hesabim");
    Route::get('/landing',[
        'uses' => 'RezervasyonController@landing',
        'as' => 'get.hours'
    ]);
    Route::post('/info/hours',[
        'uses' => 'RezervasyonController@get_empty_hours',
        'as' => 'ajax'
    ]);

    Route::get('/land',[
        'uses' => 'RezervasyonController@getview'
    ]);

      Route::get('/uzatma/{rezervasyon}',[
          'uses' => 'RezervasyonController@uzatma',
          'as' => 'rezervasyon.uzatma'
      ]);
      Route::get('/bekleme/{rezervasyon}',[
          'uses' => 'RezervasyonController@bekleme',
          'as' => 'rezervasyon.bekleme'
      ]);
    Route::resource( 'user/rezervasyon','RezervasyonController');

  });

/*
|=============================
|      --/ Home  Area /--      
|=============================
*/
  Route::group(['namespace' => 'Home'], function()
  {
    Route::get('/home','HomeController@index')->name('home'); // ana sayfa
    Route::get('/',    'HomeController@index')->name('homepage'); // ana sayfa
    Route::get('/iletisim',      'ContactsController@create')->name('contacts'); // contact sayfa 
    Route::post('/iletisim',      'ContactsController@store')->name('p_contacts'); // contact sayfa 
    Route::get('/hakkimizda',       'HomeController@aboutUs')->name('aboutUs'); // hakkimizde
    Route::get('/prices',        'HomeController@prices')->name('prices'); // kiralama fiyatlari    
    Route::get('/terms',         'HomeController@terms')->name('terms'); // Kurallar
  });




  Route::group(['namespace' => 'Settings'], function()
{
  Route::get('lang/{lang}', 'LanguageController@index')->name('lang');
});

/*
|=============================
|      --/Account Area /--      
|=============================
*/
    Route::prefix('account')->group(function()
    {
      Route::group(['namespace' => 'Account'], function()
        {
          Route::get ('/profile',         'AccountController@showprofile')->name("profile");
          Route::post('/profile',         'AccountController@profile')->name("post_profile");
          Route::get ('/change-password',  'AccountController@showchangePassword')->name('changePassword');;
          Route::post('/change-password',  'AccountController@changePassword')->name('post_changePassword');
        }
      );
    }
  );

app/Http/Controllers/Admin/ServisController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Http\Models\Servis;
use Illuminate\Http\Request;
use App\Http\Requests\ServisValidation;
use Session;
class ServisController extends Controller
{
	public function __construct()
	{
	  $this->middleware(['auth','admin']);
	}
	public function index()
	{
		$servisler = Servis::all_list();
		return view('admin.servis.index',compact('servisler'));
	}
	public function all_deleted()
	{
		$servisler =  Servis::all_deleted();
		return view('admin.servis.index',compact('servisler'));
	}
	public function tamir(Servis $servi)
	{
		$servi->durum = 2 ;
		$servi->save();
		return redirect()->back();
	}
	public function mesgul(Servis $servi)
	{
		$servi->durum = 1;
		$servi->save();
		return redirect()->back();
	}
	public function calistir(Servis $servi)
	{
		$servi->durum = 0 ;
		$servi->save();
		return redirect()->back();
	}

	public function list_rezervasyon(Servis $servi)
	{
		
	}

	public function create()
	{
		return  view('admin.servis.create');
	}

	public function store(ServisValidation $request)
	{
		$servi = new Servis;
		$servi->isim ='Servis ' . str_random(2); 
		$servi->fill($request->all());
		$servi->save();        
		Session::flash('success','yeni servis basarile oluşturuldu');
		return redirect()->route('servis.index');
	}

	public function show(Servis $servi)
	{
		return  view('admin.servis.show',compact('servi'));
		
	}

	public function edit(Servis $servi)
	{
		return  view('admin.servis.edit',compact('servi'));
	}

	public function update(ServisValidation $request, Servis $servi)
	{
		$servi->update($request->all());
		Session::flash('success',$servi->isim.' servis belgileri basarile güncellendi');        
		return redirect()->route('servis.index');
	}
	public function delete(Servis $servi)
    {
        return view('admin.servis.delete',compact('servi'));
	}
	public function p_delete( Servis $servi)
    {
		$servi->durum=9;
		$servi->save();
		Session::flash('success',$servi->isim.' servis belgileri basarile silindi');        
		return redirect()->route('servis.index');
	}
	public function restore(Servis $servi)
    {
        return view('admin.servis.delete',compact('servi'));
	}
	public function p_restore( Servis $servi)
    {
		$servi->durum=0;
		$servi->save();
		Session::flash('success',$servi->isim.' servis belgileri basarile silindi');        
		return redirect()->route('servis.index');
    }
	public function destroy(Servis $servi)
	{  	
		 $isim=$servi->isim;
		$servi->delete($servi);
		Session::flash('success',$isim.' servis belgileri basarile silinmiş');        
		return redirect()->route('servis.index');
	}
}

resources/views/admin/servis/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        <form action="{{ route('servis.store') }}" method="post" class="form-horizontal">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="sofor_adi" class="col-sm-2 control-label">Şöför Adı</label>
                                <div class="col-sm-10">
                                        <input type="text"  id="sofor_adi" name="sofor_adi"  class="form-control {{ $errors->has('sofor_adi') ? ' is-invalid' : '' }}"  value="{{ old('sofor_adi') }}" required autofocus>
                                        @if ($errors->has('sofor_adi'))
                                        <span class="invalid-feedback">
                                            <strong>{{ $errors->first('sofor_adi') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label for="sofor_numarasi" class="col-sm-2 control-label">Şöför Numarasi</label>
                                <div class="col-sm-10">
                                        <input type="text"  id="sofor_numarasi" name="sofor_numarasi"  class="form-control {{ $errors->has('sofor_numarasi') ? ' is-invalid' : '' }}"  value="{{ old('sofor_numarasi') }}" required autofocus>
                                        @if ($errors->has('sofor_numarasi'))
                                        <span class="invalid-feedback">
                                            <strong>{{ $errors->first('sofor_numarasi') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label for="plaka" class="col-sm-2 control-label">Servis Plakası</label>
                                <div class="col-sm-10">
                                        <input type="text"  id="plaka" name="plaka"  class="form-control {{ $errors->has('plaka') ? ' is-invalid' : '' }}"  value="{{ old('plaka') }}" required autofocus>
                                        @if ($errors->has('plaka'))
                                        <span class="invalid-feedback">
                                            <strong>{{ $errors->first('plaka') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            {{--<div class="hr-line-dashed"></div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label class="col-sm-2 control-label">Servis Durumu</label>--}}
                                {{--<div class="col-sm-10">--}}
                                    {{--<select class="form-control m-b" name="account">--}}
                                        {{--<option>Seç</option>--}}
                                        {{--<option>Çalışıyor</option>--}}
                                        {{--<option>Tamirde</option>--}}
                                    {{--</select>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="submit">Cancel</button>
                                    <button class="btn btn-primary" type="submit">create</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/admin/servis/delete.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">
                            @if(Route::is('servis.delete'))
                            Delete 
                            @else
                            Aktif 
                            @endif
                             <span class="text-danger"> {{ $servi->isim }} </span> servis
                    </h2>
                </div>
                <div class="panel panel-body card-body">
                    <div class="col-md-8 col-md-offset-2">
                    @if(Route::is('servis.delete'))
                    <h4 class="text-danger">{{ $servi->isim }} servisi Silmek istediğine emin misiniz ?</h4>
                    <form action="{{ route('servis.p_delete',$servi) }}" method="post">
                        @csrf
                    <div class="text-right">
                        <button type="submit" class="btn btn-danger"><i class="fa fa-2x fa-trash"></i> Sil</button>
                    </div>
                    </form>
                    @elseif(Route::is('servis.restore'))
                    <h4 class="text-success">{{ $servi->isim }} servisi aktiflemek istediğine emin misiniz ?</h4>
                    <form action="{{ route('servis.p_restore',$servi) }}" method="post">
                        @csrf
                    <div class="text-right">
                        <button type="submit" class="btn btn-success"><i class="fa fa-2x fa-check"></i> aktif</button>
                    </div>
                    </form>
                    @endif
                    <a href="{{ route('servis.index') }}" class="btn btn-default">geri dön</a>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/servis/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    
                    <div class="ibox-content">
                        <form action="{{ route("servis.update",['servi'=> $servi->id]) }}" method="post" class="form-horizontal">
                            @csrf
                            {{ method_field('put') }}
                            <div class="form-group {{ $errors->has('sofor_adi') ? ' has-error' : '' }}">
                                <label class="col-sm-2 control-label">Şöför Adı</label>
                                <div class="col-sm-10 ">
                                    <input type="text" class="form-control" name="sofor_adi" value="{{ $servi->sofor_adi }}">
                                    @if ($errors->has('sofor_adi'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('sofor_adi') }}</strong>
                                    </span>
                                    @endif
                                </div>


                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group {{ $errors->has('sofor_numarasi') ? ' has-error' : '' }}">
                                <label class="col-sm-2 control-label">Şöför Numarası</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="sofor_numarasi" value="{{ $servi->sofor_numarasi }}">

                                    @if ($errors->has('sofor_numarasi'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('sofor_numarasi') }}</strong>
                                        </span>
                                    @endif


                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group  {{ $errors->has('plaka') ? ' has-error' : '' }}">
                                <label class="col-sm-2 control-label">Servis Plakası</label>
                                <div class="col-sm-10">
                                    <input type="text" name="plaka" class="form-control" value="{{ $servi->plaka }}">
                                    @if ($errors->has('plaka'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('plaka') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Servis Durumu</label>
                                <div class="col-sm-10">
                                    <select class="form-control m-b" name="durum">
                                        <option value="0" @if($servi->durum == 0) selected @endif>Çalışıyor</option>
                                        <option value="1" @if($servi->durum == 1) selected @endif >Meşgul</option>
                                        <option value="2" @if($servi->durum == 2) selected @endif>Arzali</option>
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="submit">Cancel</button>
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/servis/index.blade.php
@extends('layouts.admin')
@section('content')

{{-- <div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
      <h2>Servisler Listesi</h2>
      <ol class="breadcrumb">
          <li>
              <a href="index.html">Home</a>
          </li>
          <li>
              <a>Servisler</a>
          </li>
          <li class="active">
              @if(Route::is('servis.index'))
              <strong>  Servisler listesi  </strong>
            @elseif(Route::is('servis.all_deleted'))
              <strong>  gizli Servisler listesi  </strong>            
            @endif 
          </li>
      </ol>
  </div>
  <div class="col-lg-2">
      <a href="{{ route('servis.create') }}" class="btn btn-primary" style="margin-top:15%">Yeni Servis Ekle</a>
  </div>
</div> --}}
<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>servisler Listesi</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>
                    <a>servisler</a>
                </li>
                <li class="active">
                  @if(Route::is('servis.index'))
                    <b>  servisler Listesi  </b>
                  @elseif(Route::is('servis.all_deleted'))
                    <b>  gizli servisler listesi  </b>            
                  @endif
                </li>
            </ol>
        </div>
        <div class="col-lg-4" style="margin-top:3%">
            <a href="{{ route('servis.create') }}" class="btn btn-primary" ><i class="fa fa-plus"></i> Ekle</a>
            @if(Route::is('servis.index'))
            <a href="{{ route('servis.all_deleted') }}" class="btn btn-danger" ><i class="fa fa-trash"></i> Silinen göster </a>
          @elseif(Route::is('servis.all_deleted'))
          <a href="{{ route('servis.index') }}" class="btn btn-success" ><i class="fa fa-check"></i> Activeler göster </a>
          @endif
        </div>
    </div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    @if($servisler)
     @foreach ($servisler as $servis)
      <div class="col-md-3 col-sm-4 col-xs-6">
          <div class="ibox">
              <div class="ibox-content product-box">

              <div class="product-imitation" style="background:no-repeat ;background-image:url('{{  asset('assets/ServisList.jpg') }}');max-width:100%;max-height:100%;">
                <span class="left-ust white-bg pad5" id="de_trash"> 
                  
                    @if(Route::is('servis.index'))
                    <a href="{{ route('servis.delete',$servis) }}" class="">
                            <i class="fa fa-trash"></i>
                    </a>
                     @elseif(Route::is('servis.all_deleted'))
                    <a href="{{ route('servis.restore',$servis) }}" class="text-success">
                        <i class="fa fa-eye"></i>
                    </a>
                    @endif
                  </span>      
            </div>
                  <div class="product-desc">
                    @if( $servis->durum == 0)
                        <small class="text-muted">Servis Durumu 
                            <b class="text-success">Çalisir</b>
                        </small>
                    @elseif( $servis->durum == 1)
                      <small class="text-muted">Servis Durumu
                          <b class="text-info">Meşgül</b>
                      </small>
                    @else
                    <small class="text-muted">Servis Durumu
                        <b class="text-danger">Arzali</b>
                    </small>
                  @endif
                   
                      <a href="#" class="product-name">{{ $servis->isim  }} </a>
                      <div class="small m-t-xs">
                          Plaka numarasi <b class="text-info"> {{ $servis->plaka  }}</b>
                          <br>
                          Şöför adi <b class="text-info"> {{ $servis->sofor_adi  }}</b>
                          <br>
                          Şöför numarasi <b class="text-info"> {{ $servis->sofor_numarasi  }}</b>
                      </div>
                      <div class="m-t text-left">
                            <a href="{{ route('rezervasyon.list',['c'=>'Servis','i'=>$servis->id]) }}" class="btn btn-xs btn-outline btn-primary">
                              Rezervasyonları 
                              <span class="hidden-sm hidden-xs"> Görüntle</span>
                              <i class="fa fa-long-arrow-right"></i>
                           </a>
                        </div>
                        <div class="form-group" style="margin-bottom:15%">
                          @if( $servis->durum == 0)
                          <div class="m-t  col-md-4 col-sm-4 col-xs-4">                                                   
                              <a href="{{ route('servis.tamir',$servis->id) }}" class="btn btn-xs btn-outline btn-danger">
                                  <span class="hidden-sm hidden-xs">Tamir</span>
                                   <i class="fa fa-long-arrow-right"></i> 
                              </a>
                          </div>
                          <div class="m-t col-md-4 col-sm-4 col-xs-4">
                              <a href="{{ route('servis.mesgul',$servis->id) }}" class="btn btn-xs btn-outline btn-info">
                                      <span class="hidden-sm hidden-xs">  Meşgul</span>
                                       <i class="fa fa-long-arrow-right"></i> 
                              </a>
                          </div>
                          @else
                          <div class="m-t col-md-4 col-sm-4 col-xs-4">                        
                              <a href="{{ route('servis.calistir',$servis->id) }}" class="btn btn-xs btn-outline btn-success">
                                      <span class="hidden-sm hidden-xs">Çalistir </span>
                                       <i class="fa fa-long-arrow-right"></i> 
                              </a>
                          </div>
                         @endif
                         <div class="m-t text-right col-md-4 col-sm-4 col-xs-4">
                              <a href="{{ route('servis.edit',$servis->id) }}" class="btn btn-xs btn-outline btn-warning">
                                  <span class="hidden-sm hidden-xs"> Düzenle </span>
                                  <i class="fa fa-edit"></i> </a>
                          </div>
                        </div>
                  </div>
              </div>
          </div>
      </div>
     @endforeach
    @else
      <div class="col-md-8 col-md-offset-2">
        <center> 
            @if(Route::is('servis.index'))
                <h2 class="text-danger alert alert-warning"> @lang('lang.dont_have') @lang('lang.servisler')</h2>
            @else
                <h2 class="text-danger alert alert-warning"> @lang('lang.dont_have') @lang('lang.hidden_servisler')</h2>
            @endif
        </center>
      </div>
      @if(Route::is('servis.index'))
        <div class="text-clear col-md-12">  </div>
        <div class="col-md-12 text-center">
            <a href="{{route('servis.create')}}" class="btn btn-success"> 
            <i class="fa fa-plus"></i>  @lang('lang.click_to') @lang('lang.add')  @lang('lang.new_servis') 
            </a>
        </div>
      @endif 
    @endif 
    
  </div>
</div>

  @endsection