routes/web.php
<?php
header('Access-Control-Allow-Origin: *');
/*
|--------------------------------------------------------------------------
|     Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/
Auth::routes();

/*
|=============================
|      --/ Admin Area /--      
|=============================
*/
Route::prefix('admin')->group(function()
{ 
  Route::group(['namespace' => 'Admin'], function()
  {
     // Admin 
    Route::get( '/', 'AdminController@index')->name("admin");

    /*****************
    * rezervasyon Routes
    ******************/
    Route::get( '/rezervasyon/list','RezervasyonController@index')->name("rezervasyon.list");
    Route::get( '/rezervasyon/simdiki','RezervasyonController@simdiki')->name("rezervasyon.simdiki");
    Route::get( '/rezervasyon/sonraki','RezervasyonController@sonraki')->name("rezervasyon.sonraki");
    Route::get( '/rezervasyon/gecmis', 'RezervasyonController@gecmis')->name("rezervasyon.gecmis");
    Route::get( '/rezervasyon/dlist','RezervasyonController@all_deleted')->name("rezervasyon.all_deleted");
    Route::get( '/rezervasyon/{rezervasyon}/delete','RezervasyonController@delete')->name("rezervasyon.delete");

    /******************
     * Kort Routes
     ******************/
    Route::get( 
      '/kort/{kort}/tamir','KortController@tamir')
      ->name("kort.tamir");
    Route::get( 
      '/kort/{kort}/mesgul','KortController@mesgul')
      ->name("kort.mesgul");
    Route::get( 
      '/kort/{kort}/calistir','KortController@calistir')
      ->name("kort.calistir");
    Route::get( 
      '/kort/{kort}/rezervasyonlar','KortController@rezervasyonlar')
      ->name("kort.rezervasyonlar");
    Route::get(
      '/kort/dlist','KortController@all_deleted')
      ->name("kort.all_deleted");
      Route::get('/kort/{kort}/delete','KortController@delete')->name("kort.delete");
      Route::post('/kort/{kort}/delete','KortController@p_delete')->name("kort.p_delete");
      Route::get('/kort/{kort}/restore','KortController@restore')->name("kort.restore");
      Route::post('/kort/{kort}/restore','KortController@p_restore')->name("kort.p_restore");
    Route::resource('/kort','KortController');
       

    /*****************
    * kiralayan Routes
    ******************/
    Route::get( '/kiralayan/dlist',  'KiralayanController@all_deleted')->name("kiralayan.all_deleted");
    Route::get( '/kiralayan/{kiralayan}/delete',  'KiralayanController@delete')->name("kiralayan.delete");    
    Route::resource( '/kiralayan',  'KiralayanController');  
   
    /*******************
     * Servis Routes
     ******************/
    Route::get( '/servis/{servi}/tamir',         'ServisController@tamir')->name("servis.tamir");
    Route::get( '/servis/{servi}/mesgul',        'ServisController@mesgul')->name("servis.mesgul");
    Route::get( '/servis/{servi}/calistir',      'ServisController@calistir')->name("servis.calistir");
    Route::get( '/servis/{servi}/rezervasyonlar','ServisController@rezervasyonlar')->name("servis.rezervasyonlar");
    Route::get('/servis/dlist',     'ServisController@all_deleted')->name("servis.all_deleted");
    Route::get('/servis/{servi}/delete', 'ServisController@delete')->name("servis.delete");
    Route::post('/servis/{servi}/delete', 'ServisController@p_delete')->name("servis.p_delete");
    Route::get('/servis/{servi}/restore', 'ServisController@restore')->name("servis.restore");
    Route::post('/servis/{servi}/restore', 'ServisController@p_restore')->name("servis.p_restore");
    Route::resource( '/servis',     'ServisController');
    
    /*****************
    * contacts Routes
    ******************/
    Route::get( '/contacts/{contacts}/delete',  'ContactsController@delete')->name("contacts.delete");    
    Route::get( '/contacts/dlist',  'ContactsController@all_deleted')->name("contacts.all_deleted");
    Route::resource( '/contacts',   'ContactsController');
  
  });
});

/*
|=============================
|      --/ User Area /--      
|=============================
*/

  Route::group(['namespace' => 'User'], function()
  {
    Route::get( 'user/', 'UserController@index')->name("user");
    Route::get( 'user/hesabim', 'UserController@hesabim')->name("hesabim");
    Route::get('/landing',[
        'uses' => 'RezervasyonController@landing',
        'as' => 'get.hours'
    ]);
    Route::post('/info/hours',[
        'uses' => 'RezervasyonController@get_empty_hours',
        'as' => 'ajax'
    ]);

    Route::get('/land',[
        'uses' => 'RezervasyonController@getview'
    ]);

      Route::get('/uzatma/{rezervasyon}',[
          'uses' => 'RezervasyonController@uzatma',
          'as' => 'rezervasyon.uzatma'
      ]);
      Route::get('/bekleme/{rezervasyon}',[
          'uses' => 'RezervasyonController@bekleme',
          'as' => 'rezervasyon.bekleme'
      ]);
    Route::resource( 'user/rezervasyon','RezervasyonController');

  });

/*
|=============================
|      --/ Home  Area /--      
|=============================
*/
  Route::group(['namespace' => 'Home'], function()
  {
    Route::get('/home','HomeController@index')->name('home'); // ana sayfa
    Route::get('/',    'HomeController@index')->name('homepage'); // ana sayfa
    Route::get('/iletisim',      'ContactsController@create')->name('contacts'); // contact sayfa 
    Route::post('/iletisim',      'ContactsController@store')->name('p_contacts'); // contact sayfa 
    Route::get('/hakkimizda',       'HomeController@aboutUs')->name('aboutUs'); // hakkimizde
    Route::get('/prices',        'HomeController@prices')->name('prices'); // kiralama fiyatlari    
    Route::get('/terms',         'HomeController@terms')->name('terms'); // Kurallar
  });




  Route::group(['namespace' => 'Settings'], function()
{
  Route::get('lang/{lang}', 'LanguageController@index')->name('lang');
});

/*
|=============================
|      --/Account Area /--      
|=============================
*/
    Route::prefix('account')->group(function()
    {
      Route::group(['namespace' => 'Account'], function()
        {
          Route::get ('/profile',         'AccountController@showprofile')->name("profile");
          Route::post('/profile',         'AccountController@profile')->name("post_profile");
          Route::get ('/change-password',  'AccountController@showchangePassword')->name('changePassword');;
          Route::post('/change-password',  'AccountController@changePassword')->name('post_changePassword');
        }
      );
    }
  );

app/Http/Controllers/Admin/ContactsController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Http\Models\Contacts;
use Illuminate\Http\Request;
use App\Http\Requests\ContactsValidation;
use Session;
class ContactsController extends Controller
{
    public function __construct()
    {
      $this->middleware(['auth','admin']);
    }
    public function index(Contacts $contacts)
    {
        $contacts = Contacts::all_list();
        return view('admin.contacts.index',compact('contacts'));
    }
    public function all_deleted()
    {
        $contacts = Contacts::all_deleted();
        return view('admin.contacts.index',compact('contacts'));
    }

    public function show(Contacts $contacts)
    {
        return  view('admin.contact.show',compact('contacts'));
    }
    public function create()
    {
        return view('admin.contacts.create');
    }

    public function edit(Contacts $contacts)
    {
        return  view('admin.contact.edit',compact('contacts'));        
    }

    public function update(ContactsValidation $request, Contacts $contacts)
    {
        
        Session:flash('success','başarile işlem gncellenmiştir');
        return redirect()->route('Acontatcs.index');
    }

    public function destroy(Contacts $contacts)
    {
        
    }

   
}

app/Http/Controllers/Home/ContactsController.php
<?php

namespace App\Http\Controllers\Home;
use App\Http\Controllers\Controller;

use App\Http\Models\Contacts;
use Illuminate\Http\Request;
use App\Http\Requests\ContactsValidation;
use Session;
class ContactsController extends Controller
{
    
    // contacts page
    public function create()
    {
        return view('home.contacts');
    }

    public function store(ContactsValidation $request)
    {
        $contact = new Contacts;
        $contact->fill($request->all());
        $contact->save();
        Session::flash('success','Sayın '.$contact->isim .' iletişim talebiniz başarile gönderilmiştir.') ;
        return redirect()->back(); 
    }   
}

resources/views/admin/contacts/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-11">
            <div class="panel">
                <div class="panel-header">create Contacts</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/contacts/delete.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Delete Contacts</div>

                <div class="card-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/contacts/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">edit Contacts</div>

                <div class="card-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/contacts/index.blade.php
@extends('layouts.admin')
@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-11">
        <div class="panel">
          <h4 class="panel-heading">
            @if(Route::is('contacts.index'))
              <center>  Contacts listesi  </center>
            @elseif(Route::is('contacts.all_deleted'))
              <center>  gizli Kiralayan listesi  </center>            
            @endif
          </h4>
          <div class="panel-body">  
            @if(count($contacts))
              <table id="DataTable" class="mdl-data-table  table-hover" cellspacing="0" width="100%">
                <thead>
                  <tr>
                      <th> @lang('lang.name')</th>
                      <th class="v-middle hidden-xs"> @lang('lang.email')</th>
                      <th class="v-middle hidden-xs"> @lang('lang.Subject')</th>
                      <th class="v-middle hidden-xs"> @lang('lang.Message')</th>
                      <th class="v-middle hidden-xs"> @lang('lang.created_at')</th>     
                      <th> @lang('lang.options')</th>
                  </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th> @lang('lang.name')</th>
                        <th class="v-middle hidden-xs"> @lang('lang.email')</th>
                        <th class="v-middle hidden-xs"> @lang('lang.Subject')</th>
                        <th class="v-middle hidden-xs"> @lang('lang.Message')</th>
                        <th class="v-middle hidden-xs"> @lang('lang.created_at')</th>     
                        <th> @lang('lang.options')</th>
                    </tr>
                </tfoot>
                <tbody>
                  @foreach ($contacts as $contact)
                    <tr>
                      <td>{{$contact->isim }}</td>
                      <td>{{$contact->email }}</td>
                      <td>{{$contact->konu }}</td>
                      <td>{{$contact->mesaj }}</td>
                      <td>{{$contact->created_at }}</td>
                      <td class="text-center">
                        <dt>
                          <a href="{{route('contacts.edit',$contact->id)}}" title="@lang('lang.edit') " class="text-info" >
                            <span class="text text-md" >
                            <i class="fa fa-edit"></i> 
                            </span>
                          </a>
                          @if(Route::is('contacts.index'))
                            <a href="#hide-file-{{$contact->id}}" title="@lang('lang.hide') " data-toggle="modal" class=" text-primary" >
                              <span class="text text-md" >
                                <i class="fa  fa-eye-slash"></i> 
                              </span>	
                            </a>
                            
                          @elseif(Route::is('contacts.all_deleted'))
                              <a href="#restore-file-{{$contact->id}}" title="@lang('lang.restore') " data-toggle="modal" class=" text-warning" >
                              <span class="text text-md" >
                                <i class="fa  fa-eye"></i> 
                              </span>	
                            </a>
                          @endif  
                            <a href="#delete-file-{{$contact->id}}" title="@lang('lang.delete') " data-toggle="modal" class=" text-danger" >
                              <span class="text text-md" >
                                <i class="fa  fa-trash"></i> 
                              </span>	
                            </a>
                        </dt>
                      </td>   
                    </tr>
                    <div class="modal fade" id="delete-file-{{$contact->id}}">
                      <div class="modal-dialog modal-shorten">
                        <div class="modal-content bg-default">
                          <div class="modal-body">
                            <div class="padder">
                              {{Form::open(array('route' =>['contacts.destroy',$contact->id],
                              'method'=>'delete','class'=>'form-delete','id'=>'form-delete' )) }}
            
                                <div class="text-center">
                                  <h4 id="msg-shorten ">@lang('lang.delete')  @lang('lang.file') </h4>
                                </div>
                                <p class="text-danger">@lang('lang.are_you_want')  @lang('lang.delete')
                                <b class="text-success">{{$contact->slug}}</b> @lang('lang.file') ?</p> 
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-rounded pull-left btn-default" data-dismiss="modal">
                                      @lang('lang.cancle')
                                  </button>
                                  <button id="btn-delete" class="btn btn-rounded  pull-right btn-success" type="submit">
                                    <i class="fa fa-trash"></i> @lang('lang.delete')
                                  </button>
                                </div>
                                {{Form::close() }}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    @if(Route::is('contacts.index'))
                      <div class="modal fade" id="hide-file-{{$contact->id}}">
                        <div class="modal-dialog modal-shorten">
                          <div class="modal-content bg-default">
                          <div class="modal-body">
                            <div class="padder">
                              {{Form::open(array('route' =>['contacts.delete',$contact->id],
                              'method'=>'delete','class'=>'form-delete','id'=>'form-delete' )) }}
          
                              <div class="text-center">
                                <h4 id="msg-shorten "> @lang('lang.hidden_contacts')</h4>
                              </div>
                              <p class="text-danger">@lang('lang.are_you_want')   @lang('lang.hide')
                                <b class="text-success">{{$contact->slug}}</b>  @lang('lang.file') ?</p> 
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-rounded pull-left btn-default" data-dismiss="modal">
                                      @lang('lang.cancle')
                                  </button>
                                  <button id="btn-delete" class="btn btn-rounded  pull-right btn-success" type="submit">
                                    <i class="fa fa-eye-slash"></i>  @lang('lang.hide')
                                  </button>
                                </div>
                                {{Form::close() }}
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    @elseif(Route::is('contacts.deletedcontacts'))
                      <div class="modal fade" id="restore-file-{{$contact->id}}">
                        <div class="modal-dialog modal-shorten">
                          <div class="modal-content bg-default">
                            <div class="modal-body">
                              <div class="padder">
                                {{Form::open(array('route' =>['contacts.restore',$contact->id], 'method'=>'post',
                                'class'=>'form-restore','id'=>'form-restore' ))
                                }}
                                <div class="text-center">
                                  <h4 id="msg-shorten "> @lang('lang.restore')  @lang('lang.file')</h4>
                                </div>
                                <hr>
                                <p>@lang('lang.are_you_want')   @lang('lang.restore')
                                  <b class="text-info">
                                    {{$contact->slug}} </b> @lang('lang.file') ?
                                  </p> 
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-rounded pull-left btn-default" data-dismiss="modal">
                                        @lang('lang.cancle')
                                    </button>
                                    <button id="btn-restore" class="btn btn-rounded  pull-right btn-success" type="submit">
                                      <i class="fa fa-eye"></i> @lang('lang.restore')
                                    </button>
                                  </div>
                                  {{Form::close() }}
                                </div>
                              </div>
                          </div>
                        </div>
                      </div>
                    @endif
                  @endforeach
                </tbody>
              </table>
            @else
              <div class="col-md-8 col-md-offset-2">
                <center> 
                    @if(Route::is('contacts.index'))
                        <h2 class="text-danger alert alert-warning"> @lang('lang.dont_have') @lang('lang.contacts')</h2>
                    @else
                        <h2 class="text-danger alert alert-warning"> @lang('lang.dont_have') @lang('lang.hidden_contacts')</h2>
                    @endif
                </center>
              </div>
            @endif 
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection